In [1]:
import pandas as pd
import requests

# 1. GET FUNDAMENTAL DATA

## 1.1 Download Fundamental Data

#### Define configurations of the collecting data

In [2]:
api_key = 'EEAI5CE759SUIP6I'
ticket = 'AAPL'

#### Income statement

In [3]:
url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={ticket}&apikey={api_key}'
r = requests.get(url)
data_is = r.json()

#### Balance Sheet

In [4]:
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol={ticket}&apikey={api_key}'
r = requests.get(url)
data_bs = r.json()

#### Cash flow

In [5]:
# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = f'https://www.alphavantage.co/query?function=CASH_FLOW&symbol={ticket}&apikey={api_key}'
r = requests.get(url)
data_cf = r.json()

#### Collect dataframe from the downloaded JSON

In [34]:
df_is = pd.json_normalize(data_is['annualReports'])
df_bs = pd.json_normalize(data_bs['annualReports'])
df_cf = pd.json_normalize(data_cf['annualReports'])

# df_is = pd.json_normalize(data_is['quarterlyReports'])
# df_bs = pd.json_normalize(data_bs['quarterlyReports'])
# df_cf = pd.json_normalize(data_cf['quarterlyReports'])

In [51]:
# print(df_is.columns)
# print(df_bs.columns)
# print(df_cf.columns)

In [36]:
df_is.head()

,fiscalDateEnding,reportedCurrency,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,...,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome
0,2023-12-31,USD,54855000000,119575000000,71506000000,64720000000,40373000000,6786000000,7696000000,14482000000,...,None,2848000000,40323000000,6407000000,None,33916000000,35990000000,40373000000,43221000000,33916000000
1,2023-09-30,USD,40427000000,88496000000,55222000000,49071000000,26969000000,6151000000,7307000000,13458000000,...,None,2653000000,26998000000,4042000000,1002000000,22956000000,23305000000,28000000000,29622000000,22956000000
2,2023-06-30,USD,36413000000,80799000000,51357000000,45384000000,22998000000,5973000000,7442000000,13415000000,...,None,3052000000,22733000000,2852000000,998000000,19881000000,19826000000,23731000000,26050000000,19881000000
3,2023-03-31,USD,41976000000,94836000000,52860000000,52860000000,28318000000,6201000000,7457000000,13658000000,...,None,2898000000,28382000000,4222000000,None,24160000000,25326000000,29312000000,31216000000,24160000000
4,2022-12-31,USD,50332000000,116151000000,73429000000,66822000000,36016000000,6607000000,7709000000,14316000000,...,None,2916000000,35623000000,5625000000,1003000000,29998000000,28195000000,36626000000,38932000000,29998000000

In [37]:
df_bs.head()

,fiscalDateEnding,reportedCurrency,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,...,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding
0,2023-12-31,USD,353514000000,143692000000,40760000000,73100000000,6511000000,50102000000,209822000000,43666000000,...,10954000000,95088000000,107998000000,54611000000,50353000000,74100000000,None,8242000000,75236000000,15460223000
1,2023-09-30,USD,352583000000,143566000000,29965000000,61555000000,6331000000,60985000000,209017000000,43715000000,...,9822000000,95281000000,111088000000,58829000000,49848000000,62146000000,None,-214000000,73812000000,15550061000
2,2023-06-30,USD,335038000000,122659000000,28408000000,62482000000,7351000000,39186000000,212379000000,43550000000,...,7216000000,98071000000,109293000000,58897000000,51730000000,60274000000,None,1408000000,70667000000,15647868000
3,2023-03-31,USD,332160000000,112913000000,24687000000,24687000000,7482000000,None,219247000000,43398000000,...,10578000000,97041000000,109615000000,56425000000,52886000000,62158000000,None,4336000000,69568000000,15723406000
4,2022-12-31,USD,346747000000,128777000000,20535000000,51355000000,6820000000,54180000000,217970000000,42951000000,...,9740000000,99627000000,111143000000,59893000000,53107000000,56727000000,None,3240000000,66399000000,15842407000

In [38]:
df_cf.head()

,fiscalDateEnding,reportedCurrency,operatingCashflow,paymentsForOperatingActivities,proceedsFromOperatingActivities,changeInOperatingLiabilities,changeInOperatingAssets,depreciationDepletionAndAmortization,capitalExpenditures,changeInReceivables,...,dividendPayoutCommonStock,dividendPayoutPreferredStock,proceedsFromIssuanceOfCommonStock,proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet,proceedsFromIssuanceOfPreferredStock,proceedsFromRepurchaseOfEquity,proceedsFromSaleOfTreasuryStock,changeInCashAndCashEquivalents,changeInExchangeRate,netIncome
0,2023-12-31,USD,39895000000,None,None,-8407000000,-9530000000,2848000000,2392000000,-11124000000,...,3825000000,None,None,0,None,-20139000000,None,None,None,33916000000
1,2023-09-30,USD,21598000000,3113000000,None,14946000000,21006000000,2653000000,2163000000,21137000000,...,3758000000,None,0,0,None,-21003000000,None,839000000,None,22956000000
2,2023-06-30,USD,26380000000,None,None,None,None,3052000000,2093000000,-3661000000,...,3849000000,None,0,0,None,0,None,2769000000,None,19881000000
3,2023-03-31,USD,28560000000,None,None,None,None,2898000000,2916000000,17786000000,...,3650000000,None,0,0,None,0,None,5155000000,None,24160000000
4,2022-12-31,USD,34005000000,703000000,None,-2186000000,-689000000,2916000000,3787000000,-6595000000,...,3768000000,None,0,0,None,-19475000000,None,-3003000000,None,29998000000

In [39]:
features_col = ['fiscalDateEnding','totalRevenue','costOfRevenue','sellingGeneralAndAdministrative','researchAndDevelopment','depreciation','interestExpense','totalCurrentLiabilities','incomeTaxExpense','netIncome','commonStockSharesOutstanding','cashAndCashEquivalentsAtCarryingValue','cashAndShortTermInvestments','operatingCashflow','totalLiabilities','inventory','currentNetReceivables','propertyPlantEquipment','capitalExpenditures','longTermInvestments','totalShareholderEquity','longTermDebt','retainedEarnings','dividendPayoutCommonStock','paymentsForRepurchaseOfCommonStock','treasuryStock','currentLongTermDebt']
df = df_is.merge(df_bs).merge(df_cf)
df = df[features_col]
df['fiscalDateEnding'] = pd.to_datetime(df.fiscalDateEnding,format='mixed')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 27 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   fiscalDateEnding                       58 non-null     datetime64[ns]
 1   totalRevenue                           58 non-null     object
 2   costOfRevenue                          58 non-null     object
 3   sellingGeneralAndAdministrative        58 non-null     object
 4   researchAndDevelopment                 58 non-null     object
 5   depreciation                           58 non-null     object
 6   interestExpense                        58 non-null     object
 7   totalCurrentLiabilities                58 non-null     object
 8   incomeTaxExpense                       58 non-null     object
 9   netIncome                              58 non-null     object
 10  commonStockSharesOutstanding           58 non-null     object
 11  cashAndCashEquivalentsAtCarryingValue  58 non-null     object
 12  cashAndShortTermInvestments            58 non-null     object
 13  operatingCashflow                      58 non-null     object
 14  totalLiabilities                       58 non-null     object
 15  inventory                              58 non-null     object
 16  currentNetReceivables                  58 non-null     object
 17  propertyPlantEquipment                 58 non-null     object
 18  capitalExpenditures                    58 non-null     object
 19  longTermInvestments                    58 non-null     object
 20  totalShareholderEquity                 58 non-null     object
 21  longTermDebt                           58 non-null     object
 22  retainedEarnings                       58 non-null     object
 23  dividendPayoutCommonStock              58 non-null     object
 24  paymentsForRepurchaseOfCommonStock     58 non-null     object
 25  treasuryStock                          58 non-null     object
 26  currentLongTermDebt                    58 non-null     object
dtypes: datetime64[ns](1), object(26)
memory usage: 12.4+ KB

#### Download stock price

In [12]:
url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol={ticket}&apikey={api_key}'
r = requests.get(url)
data_monthly_price = r.json()

In [13]:
price_monthly = pd.DataFrame.from_dict(data_monthly_price['Monthly Time Series'], orient='index')
price_monthly.columns = ['open','high','low','close','volume']
price_monthly['fiscalDateEnding'] = pd.to_datetime(price_monthly.index,format='mixed')
price_monthly.reset_index(inplace=True,drop=True)
price_monthly = price_monthly[['fiscalDateEnding','open','high','low','close','volume']]
price_monthly

    fiscalDateEnding      open      high       low     close      volume
0         2024-03-15  179.5500  180.5300  168.4900  172.6200   831573477
1         2024-02-29  183.9850  191.0500  179.2500  180.7500  1161711745
2         2024-01-31  187.1500  196.3800  180.1700  184.4000  1187139861
3         2023-12-29  190.3300  199.6200  187.4511  192.5300  1062317718
4         2023-11-30  171.0000  192.9300  170.1200  189.9500  1099760711
..               ...       ...       ...       ...       ...         ...
287       2000-04-28  135.5000  139.5000  104.8700  124.0600    77342900
288       2000-03-31  118.5600  150.3800  114.0000  135.8100    77663900
289       2000-02-29  104.0000  119.9400   97.0000  114.6200    65355200
290       2000-01-31  104.8700  121.5000   86.5000  103.7500   112099800
291       1999-12-31  101.0000  118.0000   91.0600  102.8100    84091200

[292 rows x 6 columns]

#### Merge fundamental data into price data

In [68]:
df['year'] = df.fiscalDateEnding.dt.year
df['month'] = df.fiscalDateEnding.dt.month
price_monthly['year'] = price_monthly.fiscalDateEnding.dt.year
price_monthly['month'] = price_monthly.fiscalDateEnding.dt.month
df_final = pd.merge(df,price_monthly,how="left",on=['year','month'])
df_final.drop(columns=['year','month','fiscalDateEnding_y'],inplace=True)
df_final = df_final.rename(columns={'fiscalDateEnding_x': 'date'})
df_final['tic'] = ticket

df_columns = [df_final.columns[-1]]
for i in range(0,len(df_final.columns)-1):
    df_columns.append(df_final.columns[i])
df_final = df_final[df_columns]
df_final.head()

,tic,date,totalRevenue,costOfRevenue,sellingGeneralAndAdministrative,researchAndDevelopment,depreciation,interestExpense,totalCurrentLiabilities,incomeTaxExpense,...,retainedEarnings,dividendPayoutCommonStock,paymentsForRepurchaseOfCommonStock,treasuryStock,currentLongTermDebt,open,high,low,close,volume
0,AAPL,2023-12-31,119575000000,71506000000,6786000000,7696000000,None,None,133973000000,6407000000,...,8242000000,3825000000,20139000000,None,10954000000,190.3300,199.6200,187.4511,192.5300,1062317718
1,AAPL,2023-09-30,88496000000,55222000000,6151000000,7307000000,None,1002000000,145308000000,4042000000,...,-214000000,3758000000,21003000000,None,9822000000,189.4850,189.9800,167.6200,171.2100,1337873796
2,AAPL,2023-06-30,80799000000,51357000000,5973000000,7442000000,None,998000000,124963000000,2852000000,...,1408000000,3849000000,17478000000,None,7216000000,177.7000,194.4800,176.9306,193.9700,1297863403
3,AAPL,2023-03-31,94836000000,52860000000,6201000000,7457000000,None,930000000,120075000000,4222000000,...,4336000000,3650000000,None,None,10578000000,146.8300,165.0000,143.9000,164.9000,1520461315
4,AAPL,2022-12-31,116151000000,73429000000,6607000000,7709000000,None,1003000000,137286000000,5625000000,...,3240000000,3768000000,19475000000,None,9740000000,148.2100,150.9199,125.8700,129.9300,1675731304

#### Data cleaning

Check data type

In [41]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 33 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   date                                   58 non-null     datetime64[ns]
 1   totalRevenue                           58 non-null     object
 2   costOfRevenue                          58 non-null     object
 3   sellingGeneralAndAdministrative        58 non-null     object
 4   researchAndDevelopment                 58 non-null     object
 5   depreciation                           58 non-null     object
 6   interestExpense                        58 non-null     object
 7   totalCurrentLiabilities                58 non-null     object
 8   incomeTaxExpense                       58 non-null     object
 9   netIncome                              58 non-null     object
 10  commonStockSharesOutstanding           58 non-null     object
 11  cashAndCashEquivalentsAtCarryingValue  58 non-null     object
 12  cashAndShortTermInvestments            58 non-null     object
 13  operatingCashflow                      58 non-null     object
 14  totalLiabilities                       58 non-null     object
 15  inventory                              58 non-null     object
 16  currentNetReceivables                  58 non-null     object
 17  propertyPlantEquipment                 58 non-null     object
 18  capitalExpenditures                    58 non-null     object
 19  longTermInvestments                    58 non-null     object
 20  totalShareholderEquity                 58 non-null     object
 21  longTermDebt                           58 non-null     object
 22  retainedEarnings                       58 non-null     object
 23  dividendPayoutCommonStock              58 non-null     object
 24  paymentsForRepurchaseOfCommonStock     58 non-null     object
 25  treasuryStock                          58 non-null     object
 26  currentLongTermDebt                    58 non-null     object
 27  open                                   58 non-null     object
 28  high                                   58 non-null     object
 29  low                                    58 non-null     object
 30  close                                  58 non-null     object
 31  volume                                 58 non-null     object
 32  tic                                    58 non-null     object
dtypes: datetime64[ns](1), object(32)
memory usage: 15.1+ KB

In [42]:
df_final.isna().sum()

date                                     0
totalRevenue                             0
costOfRevenue                            0
sellingGeneralAndAdministrative          0
researchAndDevelopment                   0
depreciation                             0
interestExpense                          0
totalCurrentLiabilities                  0
incomeTaxExpense                         0
netIncome                                0
commonStockSharesOutstanding             0
cashAndCashEquivalentsAtCarryingValue    0
cashAndShortTermInvestments              0
operatingCashflow                        0
totalLiabilities                         0
inventory                                0
currentNetReceivables                    0
propertyPlantEquipment                   0
capitalExpenditures                      0
longTermInvestments                      0
totalShareholderEquity                   0
longTermDebt                             0
retainedEarnings                         0
dividendPayoutCommonStock                0
paymentsForRepurchaseOfCommonStock       0
treasuryStock                            0
currentLongTermDebt                      0
open                                     0
high                                     0
low                                      0
close                                    0
volume                                   0
tic                                      0
dtype: int64

Those features, expect date in datatime64, are set in wrong format of object that require to turn them into numeric datatype.<br>
Before adjusting datatypes, checking unique values in each features is neccessary to ensure dataset clearn from missing data and nan data points

In [43]:
for i in df_final.columns:
    print(i,'\n',df_final[i].unique(),'\n')

date
 <DatetimeArray>
['2023-12-31 00:00:00', '2023-09-30 00:00:00', '2023-06-30 00:00:00',
 '2023-03-31 00:00:00', '2022-12-31 00:00:00', '2022-09-30 00:00:00',
 '2022-06-30 00:00:00', '2022-03-31 00:00:00', '2021-12-31 00:00:00',
 '2021-09-30 00:00:00', '2021-06-30 00:00:00', '2021-03-31 00:00:00',
 '2020-12-31 00:00:00', '2020-09-30 00:00:00', '2020-06-30 00:00:00',
 '2020-03-31 00:00:00', '2019-12-31 00:00:00', '2019-09-30 00:00:00',
 '2019-06-30 00:00:00', '2019-03-31 00:00:00', '2018-12-31 00:00:00',
 '2018-09-30 00:00:00', '2018-06-30 00:00:00', '2018-03-31 00:00:00',
 '2017-12-31 00:00:00', '2017-09-30 00:00:00', '2017-06-30 00:00:00',
 '2017-03-31 00:00:00', '2016-12-31 00:00:00', '2016-09-30 00:00:00',
 '2016-06-30 00:00:00', '2016-03-31 00:00:00', '2015-12-31 00:00:00',
 '2015-09-30 00:00:00', '2015-06-30 00:00:00', '2015-03-31 00:00:00',
 '2014-12-31 00:00:00', '2014-09-30 00:00:00', '2014-06-30 00:00:00',
 '2014-03-31 00:00:00', '2013-12-31 00:00:00', '2013-09-30 00:00:00',
 '2013-06-30 00:00:00', '2013-03-31 00:00:00', '2012-12-31 00:00:00',
 '2012-09-30 00:00:00', '2012-06-30 00:00:00', '2012-03-31 00:00:00',
 '2011-12-31 00:00:00', '2011-09-30 00:00:00', '2011-06-30 00:00:00',
 '2011-03-31 00:00:00', '2010-12-31 00:00:00', '2010-09-30 00:00:00',
 '2010-06-30 00:00:00', '2010-03-31 00:00:00', '2009-12-31 00:00:00',
 '2009-09-30 00:00:00']
Length: 58, dtype: datetime64[ns]

totalRevenue
 ['119575000000' '88496000000' '80799000000' '94836000000' '116151000000'
 '89319000000' '82240000000' '96587000000' '123251000000' '82688000000'
 '80769000000' '88914000000' '110801000000' '64698000000' '58988000000'
 '57556000000' '91034000000' '64040000000' '52943000000' '57005000000'
 '83420000000' '62900000000' '53265000000' '61137000000' '88293000000'
 '52579000000' '45408000000' '52896000000' '78351000000' '47858000000'
 '41949000000' '50236000000' '75596000000' '51501000000' '49404000000'
 '57847000000' '74468000000' '42123000000' '37332000000' '45561000000'
 '57510000000' '37472000000' '35270000000' '43603000000' '54512000000'
 '35966000000' '35023000000' '39186000000' '46333000000' '28270000000'
 '28571000000' '24708000000' '26741000000' '20343000000' '15700000000'
 '13499000000' '15683000000' '12207000000']

costOfRevenue
 ['71506000000' '55222000000' '51357000000' '52860000000' '73429000000'
 '58491000000' '53086000000' '60912000000' '76151000000' '53802000000'
 '51591000000' '56819000000' '72742000000' '44945000000' '41836000000'
 '40895000000' '61799000000' '44305000000' '38008000000' '40652000000'
 '57062000000' '38816000000' '32844000000' '37715000000' '54381000000'
 '32648000000' '27920000000' '32305000000' '48175000000' '40821000000'
 '29693000000' '34059000000' '49297000000' '43858000000' '33488000000'
 '37814000000' '48458000000' '36172000000' '25547000000' '30631000000'
 '38801000000' '32074000000' '24944000000' '29926000000' '36292000000'
 '26716000000' '22574000000' '22961000000' '28235000000' '20515000000'
 '18564000000' '16212000000' '18339000000' '15217000000' '11002000000'
 '9094000000' '10560000000' '7102000000']

sellingGeneralAndAdministrative
 ['6786000000' '6151000000' '5973000000' '6201000000' '6607000000'
 '6440000000' '6012000000' '6193000000' '6449000000' '5616000000'
 '5412000000' '5314000000' '5631000000' '4936000000' '4831000000'
 '4952000000' '5197000000' '4578000000' '4426000000' '4458000000'
 '4783000000' '4216000000' '4108000000' '4150000000' '4231000000'
 '3814000000' '3783000000' '3718000000' '3946000000' '3482000000'
 '3441000000' '3423000000' '3848000000' '3705000000' '3564000000'
 '3460000000' '3600000000' '3158000000' '2850000000' '2932000000'
 '3053000000' '2673000000' '2645000000' '2672000000' '2840000000'
 '2551000000' '2545000000' '2339000000' '2605000000' '2025000000'
 '1915000000' '1763000000' '1896000000' '1571000000' '1438000000'
 '1220000000' '1288000000' '1063000000']

researchAndDevelopment
 ['7696000000' '7307000000' '7442000000' '7457000000' '7709000000'
 '6761000000' '6797000000' '6387000000' '6306000000' '5772000000'
 '5717000000' '5262000000' '5163000000' '4978000000' '4758000000'
 '4565000000' '4451000000' '4110000000' '4257000000' '3948000000'
 '3902000000' '3750000000' '3701000000' '3378000000' '3407000000'
 '2997000000' '2937000000' '2776000000' '2871000000' '2570000000'
 '2560000000' '2511000000' '2404000000' '2220000000' '2034000000'
 '1918000000' '1895000000' '1686000000' '1603000000' '1422000000'
 '1330000000' '1168000000' '1178000000' '1119000000' '1010000000'
 '906000000' '876000000' '841000000' '758000000' '645000000' '628000000'
 '581000000' '575000000' '494000000' '464000000' '426000000' '398000000'
 '358000000']

depreciation
 ['None']

interestExpense
 ['None' '1002000000' '998000000' '930000000' '1003000000' '827000000'
 '719000000' '691000000' '694000000' '672000000' '665000000' '670000000'
 '638000000' '634000000' '697000000' '757000000' '785000000' '810000000'
 '866000000' '1010000000' '890000000' '868000000' '846000000' '792000000'
 '734000000' '666000000' '602000000' '530000000' '525000000' '450000000'
 '409000000' '321000000' '276000000' '238000000' '201000000' '163000000'
 '131000000' '115000000' '100000000' '85000000' '84000000' '83000000'
 '53000000' '0' '51000000' '288000000' '148000000' '137000000' '81000000'
 '172000000' '26000000' '136000000' '14000000' '58000000' '266000000'
 '33000000' '45000000']

totalCurrentLiabilities
 ['133973000000' '145308000000' '124963000000' '120075000000'
 '137286000000' '153982000000' '129873000000' '127508000000'
 '147574000000' '125481000000' '107754000000' '106385000000'
 '132507000000' '105392000000' '95318000000' '96094000000' '102161000000'
 '105718000000' '89704000000' '93772000000' '108283000000' '115929000000'
 '88548000000' '89320000000' '115788000000' '100814000000' '81302000000'
 '73342000000' '84130000000' '79006000000' '71486000000' '68265000000'
 '76092000000' '80610000000' '65285000000' '58729000000' '73611000000'
 '63448000000' '46205000000' '43208000000' '53769000000' '43658000000'
 '36319000000' '35508000000' '46879000000' '38542000000' '33060000000'
 '32036000000' '34607000000' '27970000000' '26859000000' '24327000000'
 '23795000000' '20722000000' '15612000000' '12229000000' '13097000000'
 '11506000000']

incomeTaxExpense
 ['6407000000' '4042000000' '2852000000' '4222000000' '5625000000'
 '3936000000' '3624000000' '5129000000' '6611000000' '2697000000'
 '2625000000' '4381000000' '4824000000' '2228000000' '1884000000'
 '1886000000' '3682000000' '2441000000' '1867000000' '2232000000'
 '3941000000' '2296000000' '1765000000' '2346000000' '6965000000'
 '3203000000' '2591000000' '3655000000' '6289000000' '3174000000'
 '2673000000' '3626000000' '6212000000' '3938000000' '3796000000'
 '4995000000' '6392000000' '3005000000' '2736000000' '3595000000'
 '4637000000' '2631000000' '2535000000' '3358000000' '4594000000'
 '2670000000' '3037000000' '3910000000' '4413000000' '2168000000'
 '2243000000' '1913000000' '1959000000' '1153000000' '1039000000'
 '955000000' '1380000000' '1197000000']

netIncome
 ['33916000000' '22956000000' '19881000000' '24160000000' '29998000000'
 '20721000000' '19442000000' '25010000000' '34630000000' '20551000000'
 '21744000000' '23630000000' '28755000000' '12673000000' '11253000000'
 '11249000000' '22236000000' '13686000000' '10044000000' '11561000000'
 '19965000000' '14125000000' '11519000000' '13822000000' '20065000000'
 '10714000000' '8717000000' '11029000000' '17891000000' '9014000000'
 '7796000000' '10516000000' '18361000000' '11124000000' '10677000000'
 '13569000000' '18024000000' '8467000000' '7748000000' '10223000000'
 '13072000000' '7512000000' '6900000000' '9547000000' '13078000000'
 '8223000000' '8824000000' '11622000000' '13064000000' '6623000000'
 '7308000000' '5987000000' '6004000000' '4308000000' '3253000000'
 '3074000000' '3378000000' '2532000000']

commonStockSharesOutstanding
 ['15460223000' '15550061000' '15647868000' '15723406000' '15842407000'
 '15943425000' '16095378000' '16207568000' '16340851000' '16426786000'
 '16556942000' '16686305000' '16823263000' '16976763000' '4283939000'
 '4323987000' '4384959000' '4443236000' '4531395000' '4607284000'
 '4729803000' '4754986000' '4842917000' '4943282000' '5081651000'
 '5126201000' '5169782000' '5205815000' '5255423000' '5336166000'
 '5393165000' '5478446000' '5544487000' '5578753000' '5705400000'
 '5762278000' '5826419000' '5866161000' '5989171000' '861745000'
 '892447000' '899213000' '908442000' '940094000' '938973000' '939208000'
 '937266000' '934982000' '932214000' '929277000' '926903779' '924674079'
 '921035475' '915970050' '913482347' '909635811' '906282182' '899805500']

cashAndCashEquivalentsAtCarryingValue
 ['40760000000' '29965000000' '28408000000' '24687000000' '20535000000'
 '23646000000' '27502000000' '28098000000' '37119000000' '34940000000'
 '34050000000' '38466000000' '36010000000' '38016000000' '33383000000'
 '40174000000' '39771000000' '48844000000' '50530000000' '37988000000'
 '44771000000' '25913000000' '31971000000' '45059000000' '27491000000'
 '20289000000' '18571000000' '15157000000' '16371000000' '20484000000'
 '18237000000' '21514000000' '16689000000' '21120000000' '15319000000'
 '14489000000' '19478000000' '13844000000' '12977000000' '18949000000'
 '14077000000' '14259000000' '11248000000' '12053000000' '16154000000'
 '10746000000' '7945000000' '10121000000' '10310000000' '9815000000'
 '12091000000' '15978000000' '10734000000' '11261000000' '9705000000'
 '10018000000' '7609000000' '5263000000']

cashAndShortTermInvestments
 ['73100000000' '61555000000' '62482000000' '24687000000' '51355000000'
 '48304000000' '48231000000' '51511000000' '63913000000' '62639000000'
 '61696000000' '69834000000' '76826000000' '90943000000' '93025000000'
 '94051000000' '107162000000' '100557000000' '94614000000' '80092000000'
 '86427000000' '25913000000' '70970000000' '87940000000' '77153000000'
 '74181000000' '18571000000' '15157000000' '60452000000' '67155000000'
 '61756000000' '55283000000' '38074000000' '41601000000' '34703000000'
 '33096000000' '32463000000' '25077000000' '37805000000' '41350000000'
 '40711000000' '40546000000' '42606000000' '39137000000' '39820000000'
 '29129000000' '27654000000' '28538000000' '30156000000' '25952000000'
 '28395000000' '29234000000' '26977000000' '25620000000' '24288000000'
 '23155000000' '24796000000' '23464000000']

operatingCashflow
 ['39895000000' '21598000000' '26380000000' '28560000000' '34005000000'
 '24127000000' '22892000000' '28166000000' '46966000000' '20200000000'
 '21094000000' '23981000000' '38763000000' '20576000000' '16271000000'
 '13311000000' '30516000000' '19910000000' '11636000000' '11155000000'
 '26690000000' '19523000000' '14488000000' '15130000000' '28293000000'
 '15749000000' '8672000000' '12570000000' '27234000000' '16533000000'
 '10634000000' '-9490000000' '28548000000' '-43358000000' '10677000000'
 '13569000000' '62672000000' '16009000000' '7748000000' '10919000000'
 '22670000000' '9908000000' '7828000000' '12504000000' '23426000000'
 '9136000000' '10189000000' '13977000000' '17554000000' '10429000000'
 '11108000000' '6219000000' '9773000000' '5683000000' '4801000000'
 '2330000000' '5781000000' '3110000000']

totalLiabilities
 ['279414000000' '290437000000' '274764000000' '270002000000'
 '290020000000' '302083000000' '278202000000' '283263000000'
 '309259000000' '287912000000' '265560000000' '267980000000'
 '287830000000' '258549000000' '245062000000' '241975000000'
 '251087000000' '248028000000' '225783000000' '236138000000'
 '255827000000' '258578000000' '234248000000' '240624000000'
 '266595000000' '241272000000' '212748000000' '200450000000'
 '198751000000' '193437000000' '179061000000' '174820000000'
 '165017000000' '170990000000' '147474000000' '132188000000'
 '138566000000' '120292000000' '101580000000' '85810000000' '95500000000'
 '83451000000' '76502000000' '59253000000' '68742000000' '57854000000'
 '51150000000' '48436000000' '48627000000' '39756000000' '37415000000'
 '33427000000' '32076000000' '27392000000' '21614000000' '17709000000'
 '18158000000' '15861000000']

inventory
 ['6511000000' '6331000000' '7351000000' '7482000000' '6820000000'
 '4946000000' '5433000000' '5460000000' '5876000000' '6580000000'
 '5178000000' '5219000000' '4973000000' '4061000000' '3978000000'
 '3334000000' '4097000000' '4106000000' '3355000000' '4884000000'
 '4988000000' '3956000000' '5936000000' '7662000000' '4421000000'
 '4855000000' '3146000000' '2910000000' '2712000000' '2132000000'
 '1831000000' '2281000000' '2451000000' '2349000000' '2042000000'
 '2396000000' '2283000000' '2111000000' '1594000000' '1829000000'
 '2122000000' '1764000000' '1697000000' '1245000000' '1455000000'
 '791000000' '1122000000' '1102000000' '1236000000' '776000000'
 '889000000' '930000000' '885000000' '1051000000' '942000000' '638000000'
 '576000000' '455000000']

currentNetReceivables
 ['50102000000' '60985000000' '39186000000' 'None' '54180000000'
 '60932000000' '42242000000' '45400000000' '65253000000' '51506000000'
 '33908000000' '33036000000' '58620000000' '37445000000' '32075000000'
 '30677000000' '39946000000' '45804000000' '26474000000' '26278000000'
 '36981000000' '48995000000' '26367000000' '22408000000' '50899000000'
 '35673000000' '27977000000' '29299000000' '19042000000' '19824000000'
 '24621000000' '30343000000' '19907000000' '18164000000' '29976000000'
 '27219000000' '16841000000' '9700000000' '14200000000' '13102000000'
 '8839000000' '7084000000' '11598000000' '10930000000' '7657000000'
 '7042000000' '8930000000' '5369000000' '6102000000' '5798000000'
 '6027000000' '5510000000' '3447000000' '2886000000' '3090000000'
 '3361000000']

propertyPlantEquipment
 ['43666000000' '43715000000' '43550000000' '43398000000' '42951000000'
 '42117000000' '40335000000' '39304000000' '39245000000' '39440000000'
 '38615000000' '37815000000' '37933000000' '36766000000' '35687000000'
 '35889000000' '37031000000' '37378000000' '37636000000' '38746000000'
 '39597000000' '41304000000' '38117000000' '35077000000' '33679000000'
 '33783000000' '29286000000' '27163000000' '26510000000' '27010000000'
 '25448000000' '23203000000' '22300000000' '22471000000' '21149000000'
 '20151000000' '20392000000' '20624000000' '17585000000' '15120000000'
 '15488000000' '16597000000' '16327000000' '15026000000' '15422000000'
 '15452000000' '10487000000' '8847000000' '2942000000' '7777000000'
 '2531000000' '2352000000' '2210000000' '2174000000' '2028000000'
 '3504000000' '3115000000' '1780000000']

capitalExpenditures
 ['2392000000' '2163000000' '2093000000' '2916000000' '3787000000'
 '3289000000' '2102000000' '2514000000' '2803000000' '3223000000'
 '2269000000' '3500000000' '1784000000' '1565000000' '1853000000'
 '2107000000' '2777000000' '2000000000' '2363000000' '3355000000'
 '3041000000' '3267000000' '4041000000' '2964000000' '4209000000'
 '2277000000' '2889000000' '3420000000' '4038000000' '2905000000'
 '2599000000' '4006000000' '3658000000' '2089000000' '2476000000'
 '3265000000' '3826000000' '2378000000' '1382000000' '1985000000'
 '1955000000' '1885000000' '2008000000' '2317000000' '3461000000'
 '2056000000' '1457000000' '1321000000' '1645000000' '777000000'
 '624000000' '1214000000' '760000000' '595000000' '274000000' '376000000'
 '459000000']

longTermInvestments
 ['99475000000' '100544000000' '104061000000' '110461000000' '114095000000'
 '120805000000' '131077000000' '141219000000' '138683000000'
 '127877000000' '131948000000' '134539000000' '118745000000'
 '100887000000' '100592000000' '98793000000' '99899000000' '105341000000'
 '115996000000' '145319000000' '158608000000' '170799000000'
 '172773000000' '179286000000' '207944000000' '194714000000'
 '184757000000' '189740000000' '185638000000' '170430000000'
 '169764000000' '177645000000' '177665000000' '164065000000'
 '168145000000' '160443000000' '145492000000' '130162000000'
 '126685000000' '109239000000' '118131000000' '106215000000'
 '104014000000' '105550000000' '97292000000' '92122000000' '89567000000'
 '81638000000' '67445000000' '55618000000' '47761000000' '36533000000'
 '32730000000' '25391000000' '21551000000' '18549000000' '15024000000'
 '10528000000']

totalShareholderEquity
 ['74100000000' '62146000000' '60274000000' '62158000000' '56727000000'
 '50672000000' '58107000000' '67399000000' '71932000000' '63090000000'
 '64280000000' '69178000000' '66224000000' '65339000000' '72282000000'
 '78425000000' '89531000000' '90488000000' '96456000000' '105860000000'
 '117892000000' '107147000000' '114949000000' '126878000000'
 '140199000000' '134047000000' '132425000000' '134082000000'
 '132390000000' '128249000000' '126541000000' '130457000000'
 '128267000000' '119355000000' '125677000000' '129006000000'
 '123328000000' '111547000000' '120940000000' '120179000000'
 '129684000000' '123549000000' '123354000000' '135490000000'
 '127346000000' '118210000000' '111746000000' '102498000000' '90054000000'
 '76615000000' '69343000000' '61477000000' '54666000000' '47791000000'
 '43111000000' '39348000000' '35768000000' '31640000000']

longTermDebt
 ['106000000000' '105100000000' '105300000000' '107600000000'
 '109400000000' '110087000000' '108700000000' '113000000000'
 '117800000000' '118700000000' '128339000000' '129203000000'
 '124962000000' '125873000000' '118309000000' '115992000000'
 '119324000000' '117760000000' '116029000000' '113805000000'
 '112372000000' '111984000000' '108598000000' '119598000000'
 '119998000000' '112596000000' '104795000000' '93699000000' '81199000000'
 '85200000000' '77600000000' '74900000000' '57600000000' '57400000000'
 '51200000000' '40072000000' '32504000000' '28987000000' '29030000000'
 '16962000000' '16961000000' '16960000000' '16958000000' 'None' '0']

retainedEarnings
 ['8242000000' '-214000000' '1408000000' '4336000000' '3240000000'
 '-3068000000' '5289000000' '12712000000' '14435000000' '5562000000'
 '9233000000' '15261000000' '14301000000' '14966000000' '24136000000'
 '33182000000' '43977000000' '45898000000' '53724000000' '64558000000'
 '80510000000' '70400000000' '79436000000' '91898000000' '104593000000'
 '98330000000' '98525000000' '100925000000' '100001000000' '96364000000'
 '96542000000' '102021000000' '101494000000' '92284000000' '98252000000'
 '100920000000' '97178000000' '87152000000' '98715000000' '98934000000'
 '109431000000' '104256000000' '104564000000' '116572000000'
 '109567000000' '101289000000' '95641000000' '87124000000' '75709000000'
 '62841000000' '56239000000' '49025000000' '43050000000' '37169000000'
 '32870000000' '29670000000' '26695000000' '23353000000']

dividendPayoutCommonStock
 ['3825000000' '3758000000' '3849000000' '3650000000' '3768000000'
 '3703000000' '3811000000' '3595000000' '3732000000' '3640000000'
 '3767000000' '3447000000' '3613000000' '3511000000' '3656000000'
 '3375000000' '3539000000' '3479000000' '3629000000' '3443000000'
 '3568000000' '3530000000' '3653000000' '3190000000' '3232000000'
 '3252000000' '3281000000' '2988000000' '3042000000' '3071000000'
 '3117000000' '2879000000' '2898000000' '2964000000' '3053000000'
 '2743000000' '2801000000' '2829000000' '2867000000' '2661000000'
 '2769000000' '2811000000' '2491000000' '2493000000' '2488000000' 'None']

paymentsForRepurchaseOfCommonStock
 ['20139000000' '21003000000' '17478000000' 'None' '19475000000'
 '24428000000' '21865000000' '22631000000' '20478000000' '19748000000'
 '22900000000' '18548000000' '24775000000' '17187000000' '15891000000'
 '18574000000' '20706000000' '17444000000' '16955000000' '23702000000'
 '8796000000' '19104000000' '20783000000' '22756000000' '10095000000'
 '7795000000' '7093000000' '7161000000' '10851000000' '6026000000'
 '10166000000' '6667000000' '6863000000' '13253000000' '10000000000'
 '6970000000' '5030000000' '17000000000' '5000000000' '17971000000'
 '5029000000' '4910000000' '16000000000' '0' '1950000000']

treasuryStock
 ['None']

currentLongTermDebt
 ['10954000000' '9822000000' '7216000000' '10578000000' '9740000000'

In [44]:
df_final = df_final.replace('None','0')
for i in df_final.columns:
    print(i,'\n',df_final[i].unique(),'\n')

date
 <DatetimeArray>
['2023-12-31 00:00:00', '2023-09-30 00:00:00', '2023-06-30 00:00:00',
 '2023-03-31 00:00:00', '2022-12-31 00:00:00', '2022-09-30 00:00:00',
 '2022-06-30 00:00:00', '2022-03-31 00:00:00', '2021-12-31 00:00:00',
 '2021-09-30 00:00:00', '2021-06-30 00:00:00', '2021-03-31 00:00:00',
 '2020-12-31 00:00:00', '2020-09-30 00:00:00', '2020-06-30 00:00:00',
 '2020-03-31 00:00:00', '2019-12-31 00:00:00', '2019-09-30 00:00:00',
 '2019-06-30 00:00:00', '2019-03-31 00:00:00', '2018-12-31 00:00:00',
 '2018-09-30 00:00:00', '2018-06-30 00:00:00', '2018-03-31 00:00:00',
 '2017-12-31 00:00:00', '2017-09-30 00:00:00', '2017-06-30 00:00:00',
 '2017-03-31 00:00:00', '2016-12-31 00:00:00', '2016-09-30 00:00:00',
 '2016-06-30 00:00:00', '2016-03-31 00:00:00', '2015-12-31 00:00:00',
 '2015-09-30 00:00:00', '2015-06-30 00:00:00', '2015-03-31 00:00:00',
 '2014-12-31 00:00:00', '2014-09-30 00:00:00', '2014-06-30 00:00:00',
 '2014-03-31 00:00:00', '2013-12-31 00:00:00', '2013-09-30 00:00:00',
 '2013-06-30 00:00:00', '2013-03-31 00:00:00', '2012-12-31 00:00:00',
 '2012-09-30 00:00:00', '2012-06-30 00:00:00', '2012-03-31 00:00:00',
 '2011-12-31 00:00:00', '2011-09-30 00:00:00', '2011-06-30 00:00:00',
 '2011-03-31 00:00:00', '2010-12-31 00:00:00', '2010-09-30 00:00:00',
 '2010-06-30 00:00:00', '2010-03-31 00:00:00', '2009-12-31 00:00:00',
 '2009-09-30 00:00:00']
Length: 58, dtype: datetime64[ns]

totalRevenue
 ['119575000000' '88496000000' '80799000000' '94836000000' '116151000000'
 '89319000000' '82240000000' '96587000000' '123251000000' '82688000000'
 '80769000000' '88914000000' '110801000000' '64698000000' '58988000000'
 '57556000000' '91034000000' '64040000000' '52943000000' '57005000000'
 '83420000000' '62900000000' '53265000000' '61137000000' '88293000000'
 '52579000000' '45408000000' '52896000000' '78351000000' '47858000000'
 '41949000000' '50236000000' '75596000000' '51501000000' '49404000000'
 '57847000000' '74468000000' '42123000000' '37332000000' '45561000000'
 '57510000000' '37472000000' '35270000000' '43603000000' '54512000000'
 '35966000000' '35023000000' '39186000000' '46333000000' '28270000000'
 '28571000000' '24708000000' '26741000000' '20343000000' '15700000000'
 '13499000000' '15683000000' '12207000000']

costOfRevenue
 ['71506000000' '55222000000' '51357000000' '52860000000' '73429000000'
 '58491000000' '53086000000' '60912000000' '76151000000' '53802000000'
 '51591000000' '56819000000' '72742000000' '44945000000' '41836000000'
 '40895000000' '61799000000' '44305000000' '38008000000' '40652000000'
 '57062000000' '38816000000' '32844000000' '37715000000' '54381000000'
 '32648000000' '27920000000' '32305000000' '48175000000' '40821000000'
 '29693000000' '34059000000' '49297000000' '43858000000' '33488000000'
 '37814000000' '48458000000' '36172000000' '25547000000' '30631000000'
 '38801000000' '32074000000' '24944000000' '29926000000' '36292000000'
 '26716000000' '22574000000' '22961000000' '28235000000' '20515000000'
 '18564000000' '16212000000' '18339000000' '15217000000' '11002000000'
 '9094000000' '10560000000' '7102000000']

sellingGeneralAndAdministrative
 ['6786000000' '6151000000' '5973000000' '6201000000' '6607000000'
 '6440000000' '6012000000' '6193000000' '6449000000' '5616000000'
 '5412000000' '5314000000' '5631000000' '4936000000' '4831000000'
 '4952000000' '5197000000' '4578000000' '4426000000' '4458000000'
 '4783000000' '4216000000' '4108000000' '4150000000' '4231000000'
 '3814000000' '3783000000' '3718000000' '3946000000' '3482000000'
 '3441000000' '3423000000' '3848000000' '3705000000' '3564000000'
 '3460000000' '3600000000' '3158000000' '2850000000' '2932000000'
 '3053000000' '2673000000' '2645000000' '2672000000' '2840000000'
 '2551000000' '2545000000' '2339000000' '2605000000' '2025000000'
 '1915000000' '1763000000' '1896000000' '1571000000' '1438000000'
 '1220000000' '1288000000' '1063000000']

researchAndDevelopment
 ['7696000000' '7307000000' '7442000000' '7457000000' '7709000000'
 '6761000000' '6797000000' '6387000000' '6306000000' '5772000000'
 '5717000000' '5262000000' '5163000000' '4978000000' '4758000000'
 '4565000000' '4451000000' '4110000000' '4257000000' '3948000000'
 '3902000000' '3750000000' '3701000000' '3378000000' '3407000000'
 '2997000000' '2937000000' '2776000000' '2871000000' '2570000000'
 '2560000000' '2511000000' '2404000000' '2220000000' '2034000000'
 '1918000000' '1895000000' '1686000000' '1603000000' '1422000000'
 '1330000000' '1168000000' '1178000000' '1119000000' '1010000000'
 '906000000' '876000000' '841000000' '758000000' '645000000' '628000000'
 '581000000' '575000000' '494000000' '464000000' '426000000' '398000000'
 '358000000']

depreciation
 ['0']

interestExpense
 ['0' '1002000000' '998000000' '930000000' '1003000000' '827000000'
 '719000000' '691000000' '694000000' '672000000' '665000000' '670000000'
 '638000000' '634000000' '697000000' '757000000' '785000000' '810000000'
 '866000000' '1010000000' '890000000' '868000000' '846000000' '792000000'
 '734000000' '666000000' '602000000' '530000000' '525000000' '450000000'
 '409000000' '321000000' '276000000' '238000000' '201000000' '163000000'
 '131000000' '115000000' '100000000' '85000000' '84000000' '83000000'
 '53000000' '51000000' '288000000' '148000000' '137000000' '81000000'
 '172000000' '26000000' '136000000' '14000000' '58000000' '266000000'
 '33000000' '45000000']

totalCurrentLiabilities
 ['133973000000' '145308000000' '124963000000' '120075000000'
 '137286000000' '153982000000' '129873000000' '127508000000'
 '147574000000' '125481000000' '107754000000' '106385000000'
 '132507000000' '105392000000' '95318000000' '96094000000' '102161000000'
 '105718000000' '89704000000' '93772000000' '108283000000' '115929000000'
 '88548000000' '89320000000' '115788000000' '100814000000' '81302000000'
 '73342000000' '84130000000' '79006000000' '71486000000' '68265000000'
 '76092000000' '80610000000' '65285000000' '58729000000' '73611000000'
 '63448000000' '46205000000' '43208000000' '53769000000' '43658000000'
 '36319000000' '35508000000' '46879000000' '38542000000' '33060000000'
 '32036000000' '34607000000' '27970000000' '26859000000' '24327000000'
 '23795000000' '20722000000' '15612000000' '12229000000' '13097000000'
 '11506000000']

incomeTaxExpense
 ['6407000000' '4042000000' '2852000000' '4222000000' '5625000000'
 '3936000000' '3624000000' '5129000000' '6611000000' '2697000000'
 '2625000000' '4381000000' '4824000000' '2228000000' '1884000000'
 '1886000000' '3682000000' '2441000000' '1867000000' '2232000000'
 '3941000000' '2296000000' '1765000000' '2346000000' '6965000000'
 '3203000000' '2591000000' '3655000000' '6289000000' '3174000000'
 '2673000000' '3626000000' '6212000000' '3938000000' '3796000000'
 '4995000000' '6392000000' '3005000000' '2736000000' '3595000000'
 '4637000000' '2631000000' '2535000000' '3358000000' '4594000000'
 '2670000000' '3037000000' '3910000000' '4413000000' '2168000000'
 '2243000000' '1913000000' '1959000000' '1153000000' '1039000000'
 '955000000' '1380000000' '1197000000']

netIncome
 ['33916000000' '22956000000' '19881000000' '24160000000' '29998000000'
 '20721000000' '19442000000' '25010000000' '34630000000' '20551000000'
 '21744000000' '23630000000' '28755000000' '12673000000' '11253000000'
 '11249000000' '22236000000' '13686000000' '10044000000' '11561000000'
 '19965000000' '14125000000' '11519000000' '13822000000' '20065000000'
 '10714000000' '8717000000' '11029000000' '17891000000' '9014000000'
 '7796000000' '10516000000' '18361000000' '11124000000' '10677000000'
 '13569000000' '18024000000' '8467000000' '7748000000' '10223000000'
 '13072000000' '7512000000' '6900000000' '9547000000' '13078000000'
 '8223000000' '8824000000' '11622000000' '13064000000' '6623000000'
 '7308000000' '5987000000' '6004000000' '4308000000' '3253000000'
 '3074000000' '3378000000' '2532000000']

commonStockSharesOutstanding
 ['15460223000' '15550061000' '15647868000' '15723406000' '15842407000'
 '15943425000' '16095378000' '16207568000' '16340851000' '16426786000'
 '16556942000' '16686305000' '16823263000' '16976763000' '4283939000'
 '4323987000' '4384959000' '4443236000' '4531395000' '4607284000'
 '4729803000' '4754986000' '4842917000' '4943282000' '5081651000'
 '5126201000' '5169782000' '5205815000' '5255423000' '5336166000'
 '5393165000' '5478446000' '5544487000' '5578753000' '5705400000'
 '5762278000' '5826419000' '5866161000' '5989171000' '861745000'
 '892447000' '899213000' '908442000' '940094000' '938973000' '939208000'
 '937266000' '934982000' '932214000' '929277000' '926903779' '924674079'
 '921035475' '915970050' '913482347' '909635811' '906282182' '899805500']

cashAndCashEquivalentsAtCarryingValue
 ['40760000000' '29965000000' '28408000000' '24687000000' '20535000000'
 '23646000000' '27502000000' '28098000000' '37119000000' '34940000000'
 '34050000000' '38466000000' '36010000000' '38016000000' '33383000000'
 '40174000000' '39771000000' '48844000000' '50530000000' '37988000000'
 '44771000000' '25913000000' '31971000000' '45059000000' '27491000000'
 '20289000000' '18571000000' '15157000000' '16371000000' '20484000000'
 '18237000000' '21514000000' '16689000000' '21120000000' '15319000000'
 '14489000000' '19478000000' '13844000000' '12977000000' '18949000000'
 '14077000000' '14259000000' '11248000000' '12053000000' '16154000000'
 '10746000000' '7945000000' '10121000000' '10310000000' '9815000000'
 '12091000000' '15978000000' '10734000000' '11261000000' '9705000000'
 '10018000000' '7609000000' '5263000000']

cashAndShortTermInvestments
 ['73100000000' '61555000000' '62482000000' '24687000000' '51355000000'
 '48304000000' '48231000000' '51511000000' '63913000000' '62639000000'
 '61696000000' '69834000000' '76826000000' '90943000000' '93025000000'
 '94051000000' '107162000000' '100557000000' '94614000000' '80092000000'
 '86427000000' '25913000000' '70970000000' '87940000000' '77153000000'
 '74181000000' '18571000000' '15157000000' '60452000000' '67155000000'
 '61756000000' '55283000000' '38074000000' '41601000000' '34703000000'
 '33096000000' '32463000000' '25077000000' '37805000000' '41350000000'
 '40711000000' '40546000000' '42606000000' '39137000000' '39820000000'
 '29129000000' '27654000000' '28538000000' '30156000000' '25952000000'
 '28395000000' '29234000000' '26977000000' '25620000000' '24288000000'
 '23155000000' '24796000000' '23464000000']

operatingCashflow
 ['39895000000' '21598000000' '26380000000' '28560000000' '34005000000'
 '24127000000' '22892000000' '28166000000' '46966000000' '20200000000'
 '21094000000' '23981000000' '38763000000' '20576000000' '16271000000'
 '13311000000' '30516000000' '19910000000' '11636000000' '11155000000'
 '26690000000' '19523000000' '14488000000' '15130000000' '28293000000'
 '15749000000' '8672000000' '12570000000' '27234000000' '16533000000'
 '10634000000' '-9490000000' '28548000000' '-43358000000' '10677000000'
 '13569000000' '62672000000' '16009000000' '7748000000' '10919000000'
 '22670000000' '9908000000' '7828000000' '12504000000' '23426000000'
 '9136000000' '10189000000' '13977000000' '17554000000' '10429000000'
 '11108000000' '6219000000' '9773000000' '5683000000' '4801000000'
 '2330000000' '5781000000' '3110000000']

totalLiabilities
 ['279414000000' '290437000000' '274764000000' '270002000000'
 '290020000000' '302083000000' '278202000000' '283263000000'
 '309259000000' '287912000000' '265560000000' '267980000000'
 '287830000000' '258549000000' '245062000000' '241975000000'
 '251087000000' '248028000000' '225783000000' '236138000000'
 '255827000000' '258578000000' '234248000000' '240624000000'
 '266595000000' '241272000000' '212748000000' '200450000000'
 '198751000000' '193437000000' '179061000000' '174820000000'
 '165017000000' '170990000000' '147474000000' '132188000000'
 '138566000000' '120292000000' '101580000000' '85810000000' '95500000000'
 '83451000000' '76502000000' '59253000000' '68742000000' '57854000000'
 '51150000000' '48436000000' '48627000000' '39756000000' '37415000000'
 '33427000000' '32076000000' '27392000000' '21614000000' '17709000000'
 '18158000000' '15861000000']

inventory
 ['6511000000' '6331000000' '7351000000' '7482000000' '6820000000'
 '4946000000' '5433000000' '5460000000' '5876000000' '6580000000'
 '5178000000' '5219000000' '4973000000' '4061000000' '3978000000'
 '3334000000' '4097000000' '4106000000' '3355000000' '4884000000'
 '4988000000' '3956000000' '5936000000' '7662000000' '4421000000'
 '4855000000' '3146000000' '2910000000' '2712000000' '2132000000'
 '1831000000' '2281000000' '2451000000' '2349000000' '2042000000'
 '2396000000' '2283000000' '2111000000' '1594000000' '1829000000'
 '2122000000' '1764000000' '1697000000' '1245000000' '1455000000'
 '791000000' '1122000000' '1102000000' '1236000000' '776000000'
 '889000000' '930000000' '885000000' '1051000000' '942000000' '638000000'
 '576000000' '455000000']

currentNetReceivables
 ['50102000000' '60985000000' '39186000000' '0' '54180000000' '60932000000'
 '42242000000' '45400000000' '65253000000' '51506000000' '33908000000'
 '33036000000' '58620000000' '37445000000' '32075000000' '30677000000'
 '39946000000' '45804000000' '26474000000' '26278000000' '36981000000'
 '48995000000' '26367000000' '22408000000' '50899000000' '35673000000'
 '27977000000' '29299000000' '19042000000' '19824000000' '24621000000'
 '30343000000' '19907000000' '18164000000' '29976000000' '27219000000'
 '16841000000' '9700000000' '14200000000' '13102000000' '8839000000'
 '7084000000' '11598000000' '10930000000' '7657000000' '7042000000'
 '8930000000' '5369000000' '6102000000' '5798000000' '6027000000'
 '5510000000' '3447000000' '2886000000' '3090000000' '3361000000']

propertyPlantEquipment
 ['43666000000' '43715000000' '43550000000' '43398000000' '42951000000'
 '42117000000' '40335000000' '39304000000' '39245000000' '39440000000'
 '38615000000' '37815000000' '37933000000' '36766000000' '35687000000'
 '35889000000' '37031000000' '37378000000' '37636000000' '38746000000'
 '39597000000' '41304000000' '38117000000' '35077000000' '33679000000'
 '33783000000' '29286000000' '27163000000' '26510000000' '27010000000'
 '25448000000' '23203000000' '22300000000' '22471000000' '21149000000'
 '20151000000' '20392000000' '20624000000' '17585000000' '15120000000'
 '15488000000' '16597000000' '16327000000' '15026000000' '15422000000'
 '15452000000' '10487000000' '8847000000' '2942000000' '7777000000'
 '2531000000' '2352000000' '2210000000' '2174000000' '2028000000'
 '3504000000' '3115000000' '1780000000']

capitalExpenditures
 ['2392000000' '2163000000' '2093000000' '2916000000' '3787000000'
 '3289000000' '2102000000' '2514000000' '2803000000' '3223000000'
 '2269000000' '3500000000' '1784000000' '1565000000' '1853000000'
 '2107000000' '2777000000' '2000000000' '2363000000' '3355000000'
 '3041000000' '3267000000' '4041000000' '2964000000' '4209000000'
 '2277000000' '2889000000' '3420000000' '4038000000' '2905000000'
 '2599000000' '4006000000' '3658000000' '2089000000' '2476000000'
 '3265000000' '3826000000' '2378000000' '1382000000' '1985000000'
 '1955000000' '1885000000' '2008000000' '2317000000' '3461000000'
 '2056000000' '1457000000' '1321000000' '1645000000' '777000000'
 '624000000' '1214000000' '760000000' '595000000' '274000000' '376000000'
 '459000000']

longTermInvestments
 ['99475000000' '100544000000' '104061000000' '110461000000' '114095000000'
 '120805000000' '131077000000' '141219000000' '138683000000'
 '127877000000' '131948000000' '134539000000' '118745000000'
 '100887000000' '100592000000' '98793000000' '99899000000' '105341000000'
 '115996000000' '145319000000' '158608000000' '170799000000'
 '172773000000' '179286000000' '207944000000' '194714000000'
 '184757000000' '189740000000' '185638000000' '170430000000'
 '169764000000' '177645000000' '177665000000' '164065000000'
 '168145000000' '160443000000' '145492000000' '130162000000'
 '126685000000' '109239000000' '118131000000' '106215000000'
 '104014000000' '105550000000' '97292000000' '92122000000' '89567000000'
 '81638000000' '67445000000' '55618000000' '47761000000' '36533000000'
 '32730000000' '25391000000' '21551000000' '18549000000' '15024000000'
 '10528000000']

totalShareholderEquity
 ['74100000000' '62146000000' '60274000000' '62158000000' '56727000000'
 '50672000000' '58107000000' '67399000000' '71932000000' '63090000000'
 '64280000000' '69178000000' '66224000000' '65339000000' '72282000000'
 '78425000000' '89531000000' '90488000000' '96456000000' '105860000000'
 '117892000000' '107147000000' '114949000000' '126878000000'
 '140199000000' '134047000000' '132425000000' '134082000000'
 '132390000000' '128249000000' '126541000000' '130457000000'
 '128267000000' '119355000000' '125677000000' '129006000000'
 '123328000000' '111547000000' '120940000000' '120179000000'
 '129684000000' '123549000000' '123354000000' '135490000000'
 '127346000000' '118210000000' '111746000000' '102498000000' '90054000000'
 '76615000000' '69343000000' '61477000000' '54666000000' '47791000000'
 '43111000000' '39348000000' '35768000000' '31640000000']

longTermDebt
 ['106000000000' '105100000000' '105300000000' '107600000000'
 '109400000000' '110087000000' '108700000000' '113000000000'
 '117800000000' '118700000000' '128339000000' '129203000000'
 '124962000000' '125873000000' '118309000000' '115992000000'
 '119324000000' '117760000000' '116029000000' '113805000000'
 '112372000000' '111984000000' '108598000000' '119598000000'
 '119998000000' '112596000000' '104795000000' '93699000000' '81199000000'
 '85200000000' '77600000000' '74900000000' '57600000000' '57400000000'
 '51200000000' '40072000000' '32504000000' '28987000000' '29030000000'
 '16962000000' '16961000000' '16960000000' '16958000000' '0']

retainedEarnings
 ['8242000000' '-214000000' '1408000000' '4336000000' '3240000000'
 '-3068000000' '5289000000' '12712000000' '14435000000' '5562000000'
 '9233000000' '15261000000' '14301000000' '14966000000' '24136000000'
 '33182000000' '43977000000' '45898000000' '53724000000' '64558000000'
 '80510000000' '70400000000' '79436000000' '91898000000' '104593000000'
 '98330000000' '98525000000' '100925000000' '100001000000' '96364000000'
 '96542000000' '102021000000' '101494000000' '92284000000' '98252000000'
 '100920000000' '97178000000' '87152000000' '98715000000' '98934000000'
 '109431000000' '104256000000' '104564000000' '116572000000'
 '109567000000' '101289000000' '95641000000' '87124000000' '75709000000'
 '62841000000' '56239000000' '49025000000' '43050000000' '37169000000'
 '32870000000' '29670000000' '26695000000' '23353000000']

dividendPayoutCommonStock
 ['3825000000' '3758000000' '3849000000' '3650000000' '3768000000'
 '3703000000' '3811000000' '3595000000' '3732000000' '3640000000'
 '3767000000' '3447000000' '3613000000' '3511000000' '3656000000'
 '3375000000' '3539000000' '3479000000' '3629000000' '3443000000'
 '3568000000' '3530000000' '3653000000' '3190000000' '3232000000'
 '3252000000' '3281000000' '2988000000' '3042000000' '3071000000'
 '3117000000' '2879000000' '2898000000' '2964000000' '3053000000'
 '2743000000' '2801000000' '2829000000' '2867000000' '2661000000'
 '2769000000' '2811000000' '2491000000' '2493000000' '2488000000' '0']

paymentsForRepurchaseOfCommonStock
 ['20139000000' '21003000000' '17478000000' '0' '19475000000' '24428000000'
 '21865000000' '22631000000' '20478000000' '19748000000' '22900000000'
 '18548000000' '24775000000' '17187000000' '15891000000' '18574000000'
 '20706000000' '17444000000' '16955000000' '23702000000' '8796000000'
 '19104000000' '20783000000' '22756000000' '10095000000' '7795000000'
 '7093000000' '7161000000' '10851000000' '6026000000' '10166000000'
 '6667000000' '6863000000' '13253000000' '10000000000' '6970000000'
 '5030000000' '17000000000' '5000000000' '17971000000' '5029000000'
 '4910000000' '16000000000' '1950000000']

treasuryStock
 ['0']

currentLongTermDebt
 ['10954000000' '9822000000' '7216000000' '10578000000' '9740000000'
 '11128000000' '14009000000' '9659000000' '11169000000' '9613000000'

'None' value is replaced with '0' and correcting datatype can now being apply on the features. In this case, all data points must be turned into float instead of object.

In [45]:
float_columns = df_final.columns
float_columns = float_columns.drop(['date','tic'])

for column in float_columns:
    df_final[column] = df_final[column].astype(float)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 33 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   date                                   58 non-null     datetime64[ns]
 1   totalRevenue                           58 non-null     float64
 2   costOfRevenue                          58 non-null     float64
 3   sellingGeneralAndAdministrative        58 non-null     float64
 4   researchAndDevelopment                 58 non-null     float64
 5   depreciation                           58 non-null     float64
 6   interestExpense                        58 non-null     float64
 7   totalCurrentLiabilities                58 non-null     float64
 8   incomeTaxExpense                       58 non-null     float64
 9   netIncome                              58 non-null     float64
 10  commonStockSharesOutstanding           58 non-null     float64
 11  cashAndCashEquivalentsAtCarryingValue  58 non-null     float64
 12  cashAndShortTermInvestments            58 non-null     float64
 13  operatingCashflow                      58 non-null     float64
 14  totalLiabilities                       58 non-null     float64
 15  inventory                              58 non-null     float64
 16  currentNetReceivables                  58 non-null     float64
 17  propertyPlantEquipment                 58 non-null     float64
 18  capitalExpenditures                    58 non-null     float64
 19  longTermInvestments                    58 non-null     float64
 20  totalShareholderEquity                 58 non-null     float64
 21  longTermDebt                           58 non-null     float64
 22  retainedEarnings                       58 non-null     float64
 23  dividendPayoutCommonStock              58 non-null     float64
 24  paymentsForRepurchaseOfCommonStock     58 non-null     float64
 25  treasuryStock                          58 non-null     float64
 26  currentLongTermDebt                    58 non-null     float64
 27  open                                   58 non-null     float64
 28  high                                   58 non-null     float64
 29  low                                    58 non-null     float64
 30  close                                  58 non-null     float64
 31  volume                                 58 non-null     float64
 32  tic                                    58 non-null     object
dtypes: datetime64[ns](1), float64(31), object(1)
memory usage: 15.1+ KB

## 1.2 Compute fundamental ratio

Define support functions before computing fundamental ratios

In [46]:
# Define a function to count positive values within a window
def count_positives(window):
  return window[window > 0].count()

def count_positives_window(data,k):
    df = pd.DataFrame(data, columns=['values'])

    # Create a new column with the adjusted positive count (using a shifted window)
    df['positive_count'] = df['values'].rolling(window=k, min_periods=1).apply(count_positives)

    # Set positive_count of the first k rows to positive_count of row k
    df.loc[:k-1,'positive_count'] = df.loc[k-1].positive_count

    return df

In [47]:
# Define a function to min value within a window
def get_min(window):
  return window.min()

def min_in_window(data,k):
    df = pd.DataFrame(data, columns=['values'])

    # Create a new column with the min in the window (using a shifted window)
    df['min'] = df['values'].rolling(window=k, min_periods=1).apply(get_min)

    return df

At this point, data and supporting functions are ready for computing fundamental ratios required

In [48]:
pos_count_window = 10  # number of years to look back for count_positive_profit
min_ebit_window = 4  # number of years to look back for min_ebit

gross_income = df_final.totalRevenue - df_final.costOfRevenue
ebit = gross_income - df_final.sellingGeneralAndAdministrative
profit = ebit - df_final.interestExpense - df_final.incomeTaxExpense
market_equity = df_final.commonStockSharesOutstanding * df_final.close
market_asset = df_final.totalLiabilities + market_equity

# Gross profit margin
gross_profit_margin = (gross_income/df_final.totalRevenue).to_frame('gross_profit_margin')

# SGA Expense / Gross Profit
sga_ratio = (df_final.sellingGeneralAndAdministrative/gross_income).to_frame('sga_ratio')

# Depreciation / Gross Profit
dep_ratio = (df_final.depreciation/gross_income).to_frame('dep_ratio')

# EBIT / Bond interest
ebit_on_int = (ebit/df_final.interestExpense).to_frame('ebit_on_int')

# Profit margin
profit_margin = (profit/df_final.totalRevenue).to_frame('profit_margin')

# Amount of positive profit within a window
count_positive_profit = count_positives_window(profit,pos_count_window)
count_positive_profit = count_positive_profit['positive_count'].to_frame('count_positive_profit')

# Cash And Short Term Investments / Total Liabilities
csti_on_liabilities = (df_final.cashAndShortTermInvestments/df_final.totalLiabilities).to_frame('csti_on_liabilities')

# Inventory / EBIT
inventory_on_ebit = (df_final.inventory / ebit).to_frame('inventory_on_ebit')

# Receivable / Revenue
receivable_on_rev = (df_final.currentNetReceivables / df_final.totalRevenue).to_frame('receivable_on_rev')

# ROA
roa = (profit / market_asset).to_frame('roa')

# ROE
roe = (profit / market_equity).to_frame('roe')

# Long-term debt / minEBIT
min_ebit = min_in_window(ebit,min_ebit_window)['min']
debt_on_min_ebit = (df_final.longTermDebt / min_ebit).to_frame('debt_on_min_ebit')

# Total Liabilities / Total Equity
liabilities_on_equity = (df_final.totalLiabilities / market_equity).to_frame('liabilities_on_equity')

# Capital Expenditures / EBIT
capital_cost_on_ebit = (df_final.capitalExpenditures / ebit).to_frame('capital_cost_on_ebit')

# EPS / MP
eps = profit / df_final.commonStockSharesOutstanding
eps_on_mp = (eps / df_final.close).to_frame('eps_on_mp')

# Cash and Stock Dividend & Repurchase Common / MP
dividend_on_mp = ((df_final.dividendPayoutCommonStock + df_final.paymentsForRepurchaseOfCommonStock) / df_final.close).to_frame('dividend_on_mp')

# MP / BV
mp_on_bv = (df_final.close / (df_final.cashAndShortTermInvestments + df_final.currentNetReceivables*0.8 +df_final.inventory*0.5 + df_final.propertyPlantEquipment*0.2 + df_final.longTermInvestments - df_final.totalLiabilities)).to_frame('mp_on_bv')

In [49]:
# Create a dataframe that merges all the ratios
ratios = pd.concat([df_final.date,df_final.tic,gross_profit_margin,sga_ratio,dep_ratio,
                    ebit_on_int,profit_margin,count_positive_profit,csti_on_liabilities,
                    inventory_on_ebit,receivable_on_rev,roa,roe,debt_on_min_ebit,
                   liabilities_on_equity,capital_cost_on_ebit,eps_on_mp,dividend_on_mp,mp_on_bv], axis=1)

In [50]:
ratios

,date,tic,gross_profit_margin,sga_ratio,dep_ratio,ebit_on_int,profit_margin,count_positive_profit,csti_on_liabilities,inventory_on_ebit,receivable_on_rev,roa,roe,debt_on_min_ebit,liabilities_on_equity,capital_cost_on_ebit,eps_on_mp,dividend_on_mp,mp_on_bv
0,2023-12-31,AAPL,0.401999,0.141172,0.0,inf,0.291666,10.0,0.261619,0.157716,0.419001,0.010711,0.011717,2.567643,0.093872,0.057942,0.011717,1.244689e+08,-3.515329e-09
1,2023-09-30,AAPL,0.375994,0.184859,0.0,27.068862,0.249492,10.0,0.211939,0.233418,0.689127,0.007477,0.008293,3.874940,0.109091,0.079748,0.008293,1.446236e+08,-2.531138e-09
2,2023-06-30,AAPL,0.364386,0.202873,0.0,23.516032,0.242812,10.0,0.227402,0.313222,0.484981,0.005927,0.006464,4.486770,0.090525,0.089181,0.006464,1.099500e+08,-3.007907e-09
3,2023-03-31,AAPL,0.442617,0.147727,0.0,38.467742,0.322905,10.0,0.091433,0.209140,0.000000,0.010697,0.011811,4.584771,0.104136,0.081509,0.011811,2.213463e+07,-1.346855e-09
4,2022-12-31,AAPL,0.367814,0.154651,0.0,36.006979,0.253868,10.0,0.177074,0.188841,0.466462,0.012556,0.014325,4.661468,0.140896,0.104859,0.014325,1.788886e+08,-1.876901e-09
5,2022-09-30,AAPL,0.345145,0.208901,0.0,29.489722,0.219718,10.0,0.159903,0.202805,0.682184,0.007833,0.008907,4.690741,0.137100,0.134861,0.008907,2.035528e+08,-1.884580e-09
6,2022-06-30,AAPL,0.354499,0.206215,0.0,32.186370,0.228587,10.0,0.173367,0.234768,0.513643,0.007584,0.008543,4.697088,0.126423,0.090831,0.008543,1.877999e+08,-2.517080e-09
7,2022-03-31,AAPL,0.369356,0.173595,0.0,42.665702,0.244981,10.0,0.181849,0.185198,0.470043,0.007600,0.008361,4.882897,0.100093,0.085272,0.008361,1.501976e+08,-4.002778e-09
8,2021-12-31,AAPL,0.382147,0.136921,0.0,58.574928,0.270554,10.0,0.206665,0.144547,0.529432,0.010385,0.011492,5.090312,0.106581,0.068953,0.011492,1.363406e+08,-4.065843e-09
9,2021-09-30,AAPL,0.349337,0.194419,0.0,34.627976,0.240676,10.0,0.217563,0.282768,0.622896,0.007618,0.008562,5.129202,0.123866,0.138505,0.008562,1.652862e+08,-3.143522e-09
10,2021-06-30,AAPL,0.361252,0.185482,0.0,35.738346,0.253513,10.0,0.232324,0.217874,0.419815,0.008083,0.009030,5.515213,0.117109,0.088067,0.009030,1.947065e+08,-3.972434e-09
11,2021-03-31,AAPL,0.360967,0.165571,0.0,39.971642,0.244393,10.0,0.260594,0.194877,0.371550,0.009422,0.010661,5.552342,0.131477,0.084724,0.010661,1.800655e+08,-4.523119e-09
12,2020-12-31,AAPL,0.343490,0.147954,0.0,50.827586,0.243373,10.0,0.266914,0.153355,0.529057,0.010700,0.012080,5.370090,0.128940,0.107931,0.012080,2.139423e+08,-3.759999e-09
13,2020-09-30,AAPL,0.305311,0.249886,0.0,23.370662,0.184782,10.0,0.351744,0.274077,0.578766,0.005374,0.006081,8.495174,0.131505,0.120402,0.006081,1.787238e+08,-4.229838e-09
14,2020-06-30,AAPL,0.290771,0.281658,0.0,17.677188,0.165118,10.0,0.379598,0.322863,0.543755,0.005388,0.006232,9.602224,0.156811,0.127019,0.006232,5.358279e+07,-2.189860e-08
15,2020-03-31,AAPL,0.289475,0.297221,0.0,15.467635,0.157516,10.0,0.388681,0.284738,0.532994,0.006758,0.008245,9.906226,0.220068,0.158254,0.008245,8.631484e+07,-1.615093e-08
16,2019-12-31,AAPL,0.321144,0.177766,0.0,30.621656,0.214986,10.0,0.426792,0.170438,0.438803,0.012719,0.015199,10.190793,0.194997,0.087653,0.015199,8.256428e+07,-1.123159e-07
17,2019-09-30,AAPL,0.308167,0.231974,0.0,18.712346,0.185915,10.0,0.405426,0.270898,0.715240,0.009577,0.011964,10.057221,0.249236,0.183216,0.011964,9.341876e+07,5.541343e-08
18,2019-06-30,AAPL,0.282096,0.296351,0.0,12.135104,0.146875,10.0,0.419048,0.319250,0.500047,0.006927,0.008670,11.040917,0.251750,0.190313,0.008670,1.040016e+08,1.301172e-08
19,2019-03-31,AAPL,0.286870,0.272611,0.0,11.777228,0.151794,10.0,0.339175,0.410593,0.460977,0.007786,0.009887,10.829289,0.269825,0.198655,0.009887,1.429060e+08,9.271914e-09
20,2018-12-31,AAPL,0.315967,0.181463,0.0,24.241573,0.200719,10.0,0.337834,0.231194,0.443311,0.016712,0.022443,10.692930,0.342895,0.155504,0.022443,7.838215e+07,5.400908e-09
21,2018-09-30,AAPL,0.382893,0.175054,0.0,22.889401,0.265564,10.0,0.100213,0.199114,0.778935,0.012541,0.015562,10.656009,0.240898,0.153060,0.015562,1.002658e+08,-1.815915e-08
22,2018-06-30,AAPL,0.383385,0.201165,0.0,19.282506,0.257242,10.0,0.302970,0.363882,0.495015,0.012118,0.015284,9.129718,0.261300,0.200270,0.015284,1.320080e+08,4.495143e-09
23,2018-03-31,AAPL,0.383107,0.177184,0.0,24.333333,0.263899,10.0,0.365466,0.397572,0.366521,0.015078,0.019453,7.331453,0.290124,0.209682,0.019453,1.546430e+08,3.029898e-09
24,2017-12-31,AAPL,0.384085,0.124764,0.0,40.437330,0.248967,10.0,0.289402,0.148951,0.576478,0.019512,0.025561,7.355974,0.310006,0.099862,0.025561,7.875081e+07,2.482561e-09
25,2017-09-30,AAPL,0.379068,0.191360,0.0,24.199700,0.232945,10.0,0.307458,0.301235,0.678465,0.011876,0.015503,6.986164,0.305388,0.261153,0.015503,7.167791e+07,2.358540e-09
26,2017-06-30,AAPL,0.385130,0.216320,0.0,22.765781,0.231501,10.0,0.087291,0.229551,0.000000,0.010981,0.014119,7.646479,0.285740,0.166144,0.014119,7.203166e+07,-7.237913e-08
27,2017-03-31,AAPL,0.389273,0.180564,0.0,31.835849,0.239867,10.0,0.075615,0.172465,0.000000,0.013379,0.016966,6.836848,0.268029,0.171220,0.016966,7.064597e+07,1.267447e-08
28,2016-12-31,AAPL,0.385139,0.130766,0.0,49.961905,0.247808,10.0,0.304159,0.103393,0.357073,0.024047,0.031898,5.924772,0.326526,0.130385,0.031898,1.199534e+08,1.516393e-09
29,2016-09-30,AAPL,0.147039,0.494813,0.0,7.900000,-0.001442,9.0,0.347167,0.599719,0.612207,-0.000087,-0.000114,23.966245,0.320656,1.135865,-0.000114,8.046882e+07,1.526564e-09
30,2016-06-30,AAPL,0.292164,0.280760,0.0,21.552567,0.136666,9.0,0.344888,0.207714,0.453932,0.008253,0.011119,21.828411,0.347296,0.329552,0.011119,1.389435e+08,1.297191e-09
31,2016-03-31,AAPL,0.322020,0.211597,0.0,39.732087,0.175313,9.0,0.316228,0.178846,0.394617,0.011409,0.014750,21.068917,0.292784,0.203779,0.014750,8.758602e+07,1.366675e-09
32,2015-12-31,AAPL,0.347889,0.146317,0.0,81.344203,0.211162,9.0,0.230728,0.109171,0.325692,0.021323,0.027352,16.202532,0.282751,0.178433,0.027352,9.273228e+07,1.383102e-09
33,2015-09-30,AAPL,0.148405,0.484757,0.0,16.546218,-0.004621,8.0,0.243295,0.596496,0.589173,-0.000303,-0.000388,14.575927,0.278765,0.928898,-0.000388,1.474943e+08,1.701509e-09
34,2015-06-30,AAPL,0.322160,0.223926,0.0,61.452736,0.169116,8.0,0.235316,0.165317,0.402943,0.009681,0.011676,13.001524,0.206084,0.169122,0.011676,1.040702e+08,1.638463e-09
35,2015-03-31,AAPL,0.346310,0.172715,0.0,101.674847,0.197331,8.0,0.250371,0.144572,0.314001,0.013442,0.015920,10.175724,0.184363,0.149400,0.015920,7.805995e+07,1.534082e-09
36,2014-12-31,AAPL,0.349278,0.138408,0.0,171.068702,0.213340,8.0,0.234278,0.101874,0.402535,0.020324,0.024703,8.253936,0.215459,0.145694,0.024703,7.094582e+07,1.609280e-09
37,2014-09-30,AAPL,0.141277,0.530667,0.0,24.286957,-0.007763,7.0,0.208468,0.755818,0.646179,-0.000460,-0.000553,10.378446,0.203534,1.369853,-0.000553,1.968139e+08,1.627559e-09
38,2014-06-30,AAPL,0.315681,0.241833,0.0,89.350000,0.163372,7.0,0.372170,0.178400,0.451114,0.009267,0.010958,10.393842,0.182510,0.266144,0.010958,8.465512e+07,1.151595e-09
39,2014-03-31,AAPL,0.327693,0.196383,0.0,141.152941,0.182568,8.0,0.481879,0.152442,0.212901,0.015169,0.017984,6.073040,0.185522,0.115186,0.017984,3.843947e+07,7.018273e-09
40,2013-12-31,AAPL,0.325317,0.163183,0.0,186.380952,0.190141,8.0,0.426293,0.135539,0.246914,0.018342,0.021840,6.072682,0.190740,0.126788,0.021840,1.389968e+07,7.114072e-09
41,2013-09-30,AAPL,0.144054,0.495183,0.0,32.831325,0.000294,8.0,0.485866,0.647339,0.349648,0.000021,0.000026,6.223853,0.194661,0.717431,0.000026,1.610697e+07,6.112728e-09
42,2013-06-30,AAPL,0.292770,0.256150,0.0,144.924528,0.144400,8.0,0.556927,0.220935,0.250610,0.011662,0.014138,6.223119,0.212373,0.245411,0.014138,4.743903e+07,4.877182e-09
43,2013-03-31,AAPL,0.313671,0.195364,0.0,inf,0.175378,9.0,0.660507,0.113130,0.162466,0.016086,0.018376,0.000000,0.142386,0.182463,0.018376,5.627344e+06,4.672914e-09
44,2012-12-31,AAPL,0.334238,0.155873,0.0,inf,0.197865,9.0,0.579267,0.094603,0.212760,0.018975,0.021585,0.000000,0.137568,0.150650,0.021585,8.348790e+06,6.532911e-09
45,2012-09-30,AAPL,0.257187,0.275784,0.0,131.352941,0.110604,9.0,0.503492,0.118077,0.303898,0.005812,0.006349,0.000000,0.092337,0.516644,0.006349,3.729548e+06,8.821002e-09
46,2012-06-30,AAPL,0.355452,0.204434,0.0,34.388889,0.187848,9.0,0.540645,0.113288,0.218628,0.010992,0.012019,0.000000,0.093448,0.207593,0.012019,0.000000e+00,7.801750e-09
47,2012-03-31,AAPL,0.414051,0.144160,0.0,93.824324,0.250804,10.0,0.589190,0.079361,0.179707,0.016138,0.017532,0.000000,0.086405,0.104926,0.017532,0.000000e+00,8.602606e-09
48,2011-12-31,AAPL,0.390607,0.143939,0.0,113.087591,0.236182,10.0,0.620149,0.079778,0.192735,0.025677,0.028984,0.000000,0.128797,0.085264,0.028984,0.000000e+00,7.065054e-09
49,2011-09-30,AAPL,0.274319,0.261122,0.0,70.740741,0.123134,10.0,0.652782,0.135428,0.189919,0.008833,0.009824,0.000000,0.112194,0.287086,0.009824,0.000000e+00,7.935471e-09
50,2011-06-30,AAPL,0.350250,0.191366,0.0,47.046512,0.198698,10.0,0.758920,0.109862,0.213573,0.016288,0.018246,0.000000,0.120254,0.096021,0.018246,0.000000e+00,7.530741e-09
51,2011-03-31,AAPL,0.343856,0.207509,0.0,258.961538,0.194026,10.0,0.874562,0.138126,0.234661,0.013478,0.014876,0.000000,0.103728,0.092678,0.014876,0.000000e+00,9.192102e-09
52,2010-12-31,AAPL,0.314199,0.225661,0.0,47.838235,0.164953,10.0,0.841034,0.136028,0.225384,0.013401,0.014847,0.000000,0.107968,0.186597,0.014847,0.000000e+00,9.675707e-09
53,2010-09-30,AAPL,0.251979,0.306477,0.0,253.928571,0.117387,10.0,0.935310,0.295640,0.270855,0.008312,0.009188,0.000000,0.105392,0.213783,0.009188,0.000000e+00,9.788770e-09
54,2010-06-30,AAPL,0.299236,0.306088,0.0,56.206897,0.137771,10.0,1.123716,0.288957,0.219554,0.008604,0.009414,0.000000,0.094069,0.182515,0.009414,0.000000e+00,9.028615e-09
55,2010-03-31,AAPL,0.326320,0.276958,0.0,11.973684,0.145492,10.0,1.307527,0.200314,0.213794,0.008485,0.009188,0.000000,0.082844,0.086028,0.009188,0.000000e+00,8.600624e-09
56,2009-12-31,AAPL,0.326659,0.251415,0.0,116.212121,0.154435,10.0,1.365569,0.150196,0.197029,0.011581,0.012682,0.000000,0.095077,0.098044,0.012682,0.000000e+00,8.414135e-09
57,2009-09-30,AAPL,0.418203,0.208227,0.0,89.822222,0.229377,10.0,1.479352,0.112568,0.275334,0.015331,0.016789,0.000000,0.095102,0.113558,0.016789,0.000000e+00,8.659880e-09